@startuml
autonumber
skinparam WrapWidth 150
skinparam MaxMessageSize 150

title Authentication Flow
actor User as user
participant "Angular App" as app #red
participant Okta as okta #deepskyblue
participant "Spring Back End" as back #springgreen
database Database as db #darkorange

autonumber stop
group Performed only once as the back end starts
    back -> okta: Request for Okta public key
    okta --> back: Okta public key
end

autonumber
user -> app: Opens app
app -> app: Check for access token
note left: On initial load, there will be no access token

group If there is no access token
    app -> user: Angular app serves Okta login boxes
    user -> app: User credentials
    app -> okta: User credentials + client credentials
    okta -> okta: Validate client credentials
    okta -> okta: Validate user credentials
    okta --> app: Authorization code
    app -> okta: Authorization code + Client credentials
    note right: Client credentials identify the angular app to the Okta
    okta --> app: Access token
end

app -> back: Request with access token
back -> back: Validate access token against Okta public key

group If access token is invalid
    back --> app: 403 forbidden response
    app --> user: Authentication error
end

autonumber 13
back -> db: SQL Query
db --> back: Data
back --> app: Response
app --> user: Home page with relevant data
@enduml
