@startuml
skinparam WrapWidth 250
skinparam MaxMessageSize 250
title Data Model

' hide "E" circle around all entities
hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

package Okta <<Rectangle>> {
    entity "**USER**" as u {
        * **id**: varchar
        --
        * **user_type**: varchar ("ADMIN", "TEACHER", "STUDENT")
        * **first_name**: varchar
        * **last_name**: varchar
        * **email_address**: varchar
    }
    note right
        Not an actual entity in Okta, but represented here for the purposes of system clarity
    end note
}

package Database <<Database>> {
    entity "**COURSE**" as c {
        * **id**: int
        --
        * **course_title**: varchar
        * **description**: varchar
        * **course_code**: varchar
    }

    entity "**COURSE_MEMBERS**" as cm {
        * **id**: int
        --
        * **course_id**: int <<FK: COURSE>>
        * **user_id**: varchar
    }

    entity "**COURSE_CONTENT**" as cc {
        * **id**: int
        --
        * **creation_date**: datetime2
        * **last_update_date**: datetime2
        * **is_public**: char(1) ("1"/"0")
        **course_id**: int <<FK: COURSE>>
        **content**: ntext
    }

}

cm ---> u
cm ---> c
cc ---> c
@enduml
