@startuml
skinparam WrapWidth 250
skinparam MaxMessageSize 250
footer Generated on %date("MM-dd-YYYY")
title Data Model

' hide "E" circle around all entities
hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

package Okta <<Rectangle>> {
    entity "**USER**" as u {
        * **id**: varchar
        --
        * **user_type**: varchar ("ADMIN", "TEACHER", "STUDENT")
        * **first_name**: varchar
        * **last_name**: varchar
        * **email_address**: varchar
    }
    note right
        Not an actual entity in Okta, but represented here for the purposes of system clarity
    end note
}

package Database <<Database>> {
    entity "**COURSE**" as c {
        * **id**: int
        --
        * **course_title**: varchar(max)
    }

    entity "**COURSE_MEMBERS**" as cm {
        * **id**: int
        --
        * **course_id**: int <<FK: COURSE>>
        * **user_id**: varchar
    }

    entity "**COURSE_CONTENT**" as cc {
        * **id**: int
        --
        * **creation_date**: datetime2
        * **last_update_date**: datetime2
        * **is_public**: char(1) ("1"/"0")
        **course_id**: int <<FK: COURSE>>
        **content**: nvarchar
    }

    entity "**QUIZ**" as q {
        * **id**: int
        --
        * **course_id** int <<FK: COURSE>>
        * **due_duate** datetime
        * **last_update_date**: datetime2
        **number_of_attempts**: int
        **title**: varchar
    }

    entity "**QUIZ_QUESTION**" as qq {
        * **id**: int
        --
        * **quiz_id**: int <<FK: QUIZ>>
        * **label**: nvarchar
        * **question_type**: varchar ("MultipleChoice"/TrueFalse")
        **truefalse_correct_answer**: char(1) ("1"/"0")
        **sort_order**: int
    }

    entity "**QUIZ_ANSWER**" as qa {
        * **id**: int
        --
        * **label**: nvarchar
        * **question_id**: int <<FK: QUIZ_QUESTION>>
        * **is_correct_answer**: char(1) ("1"/"0")
        **sort_order**: int
    }

    entity "**ASSIGNMENT**" as a {
        * **id**: int
        --
        * **course_id** int <<FK: COURSE>>
        * **due_date** datetime
        * **allowed_submissions** int
        * **title**: varchar
        **description**: nvarchar
    }

    entity "**ASSIGNMENT_SUBMISSION**" as as {
        * **id**: int
        --
        * **assignment_id** int <<FK: ASSIGNMENT>>
        * **user_id** varchar
    }
    note left
        Not finalized yet, since unsure of mechanism to submit assignments
    end note

    entity "**GRADE**" as g {
        * **user_id**: varchar
        **quiz_id**: id <<FK: QUIZ>>
        **assignment_id**: id <<FK: ASSIGNMENT>>
    }
}

cm ---> u
cm ---> c
cc ---> c
q ---> c
qq ---> q
qa ---> qq
a ---> c
as ---> a
as ---> u
g ---> u
g ---> q
g ---> a
@enduml
